// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindPowerSystemV3.Repositories;

namespace WindPowerSystemV3.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210423142932_AddTurbine")]
    partial class AddTurbine
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WindPowerSystemV3.Repositories.Models.Turbine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProdMW");

                    b.Property<string>("SerialNum")
                        .IsRequired();

                    b.Property<int>("TurbineTypeId");

                    b.HasKey("Id");

                    b.HasIndex("TurbineTypeId");

                    b.ToTable("Turbines");
                });

            modelBuilder.Entity("WindPowerSystemV3.Repositories.Models.TurbineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Capacity");

                    b.Property<string>("Model")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TurbineTypes");
                });

            modelBuilder.Entity("WindPowerSystemV3.Repositories.Models.Turbine", b =>
                {
                    b.HasOne("WindPowerSystemV3.Repositories.Models.TurbineType", "TurbineType")
                        .WithMany()
                        .HasForeignKey("TurbineTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
